CREATE TABLE truck_data (
    id SERIAL PRIMARY KEY,
    truck_id VARCHAR(50) NOT NULL,
    location VARCHAR(150) NOT NULL,
    speed FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);